sonar.organization=gauravbanga2025
sonar.projectKey=gauravbanga2025_ai-chatbot-cloud-orchestrator
sonar.projectName=ai-chatbot-cloud-orchestrator
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
sonar.sourceEncoding=UTF-8
